export default [
  {
    Code: "1",
    StudnetName: "وليد السيد عبد المبدى حجازى",
    StudentId: "140835",
    Attendance: [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 0,
    totalAttendance: 0,
    Participation: "0",
    View: false,
  },
  {
    Code: "2",
    StudnetName: "سماح عبد الحكيم عامر خضراوى",
    StudentId: "141034",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "3",
    StudnetName: "يوسف جابر ربيع جودة",
    StudentId: "1527276",
    Attendance: [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 0,
    totalAttendance: 0,
    Participation: "0",
    View: false,
  },
  {
    Code: "4",
    StudnetName: "احمد عامر احمد عبد الرازق عفيفى",
    StudentId: "1627003",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "5",
    StudnetName: "عمر محمد ابو المكارم متولى",
    StudentId: "1627054",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "6",
    StudnetName: "اسراء محمود عصمت حنفى محمود سليمان",
    StudentId: "1627199",
    Attendance: [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "7",
    StudnetName: "محمد محمود رشاد محمد",
    StudentId: "1627212",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "8",
    StudnetName: "رانيا اشرف محمود احمد",
    StudentId: "1627213",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "9",
    StudnetName: "عمر عبد الرازق محمد قبيصى محمد",
    StudentId: "1627243",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "10",
    StudnetName: "كريم السيد احمد محمد الكاشف",
    StudentId: "1727098",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "11",
    StudnetName: "عبد الرحمن على محمد على حجو",
    StudentId: "1727103",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "12",
    StudnetName: "يمنى ايمن محمد وحيد الدين",
    StudentId: "1727108",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "13",
    StudnetName: "يوسف ايهاب زكريا عبدالمنعم",
    StudentId: "1727139",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "14",
    StudnetName: "هايدى سعيد عبد الله سعيد",
    StudentId: "1727143",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "15",
    StudnetName: "اسلام عابد على محمد",
    StudentId: "1727150",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "16",
    StudnetName: "احمد جمال احمد زكى",
    StudentId: "1727163",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "17",
    StudnetName: "محمد عبد الناصر رجب عمر غنيم",
    StudentId: "1727181",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "18",
    StudnetName: "احمد حنفى عبد الفتاح دمرداش ابوجبل",
    StudentId: "1727218",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "19",
    StudnetName: "عمر احمد مصطفى جوهرى",
    StudentId: "1727247",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "20",
    StudnetName: "شروق سعيد احمد السيد",
    StudentId: "1727258",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "21",
    StudnetName: "اسراء مجدى عبد الهادى",
    StudentId: "1727265",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "22",
    StudnetName: "احمد محمد احمد خضير",
    StudentId: "1827001",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "23",
    StudnetName: "محمد سعيد عبد الحميد بدر",
    StudentId: "1827002",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "24",
    StudnetName: "ايه شريف محمد محمد على",
    StudentId: "1827008",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "25",
    StudnetName: "شيرين رضا محمد السيدهاشم",
    StudentId: "1827010",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "26",
    StudnetName: "عاصم مسعد سيد زيدان",
    StudentId: "1827012",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "27",
    StudnetName: "مصطفى احمد عبد الحافظ سليم",
    StudentId: "1827013",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "28",
    StudnetName: "مارينا عبد الملاك بشاره سعد",
    StudentId: "1827014",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "29",
    StudnetName: "مى محمد احمد حسن رفاعى",
    StudentId: "1827016",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "30",
    StudnetName: "هيام صلاح عزيز محمد على",
    StudentId: "1827022",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "31",
    StudnetName: "عمر عبد الباسط طه محمد",
    StudentId: "1827025",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "32",
    StudnetName: "عبد الرحمن محمد سيد احمد بيومي",
    StudentId: "1827027",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "33",
    StudnetName: "احمد محمد احمد عبد الشكور",
    StudentId: "1827028",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "34",
    StudnetName: "يوسف مجدى عبده سويلم",
    StudentId: "1827034",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "35",
    StudnetName: "احمد سيد عبد الحميد عبد الحميد",
    StudentId: "1827036",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "36",
    StudnetName: "محمود سعد احمد محمد",
    StudentId: "1827040",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "37",
    StudnetName: "اية عباس محمد كرار",
    StudentId: "1827042",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "38",
    StudnetName: "اسراء عبد الناصر محمد حسن",
    StudentId: "1827054",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "39",
    StudnetName: "اسلام محى الدين عبد الباقى امام وهبه",
    StudentId: "1827057",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "40",
    StudnetName: "محمد خالد حماد على",
    StudentId: "1827068",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "41",
    StudnetName: "ايه صبحي محمد احمد",
    StudentId: "1827074",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "42",
    StudnetName: "زينب محمد عوض فرج",
    StudentId: "1827091",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "43",
    StudnetName: "احمد اشرف محمد احمد",
    StudentId: "1827095",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "44",
    StudnetName: "هيام طارق فتحى محمد على",
    StudentId: "1827119",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "45",
    StudnetName: "سلفيا عماد حلمى صادق",
    StudentId: "1827120",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "46",
    StudnetName: "محمود محمد ابوالفتوح محمد",
    StudentId: "1827126",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "47",
    StudnetName: "يوسف علاءالدين محمد محمود",
    StudentId: "1827127",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "48",
    StudnetName: "عمرو وجيه محمد السعيد عبدالرحمن",
    StudentId: "1827133",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "49",
    StudnetName: "الاء محمود نصر محمد عبد الله",
    StudentId: "1827137",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "50",
    StudnetName: "ايمان محمد مصطفى كمال عبد الفتاح",
    StudentId: "1827138",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "51",
    StudnetName: "ساره سمير عبدالقادر عبد العليم طايل",
    StudentId: "1827150",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "52",
    StudnetName: "بسمله محمد السيد مرسي كشك",
    StudentId: "1827154",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "53",
    StudnetName: "دعاء عبده حسين حامد",
    StudentId: "1827181",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "54",
    StudnetName: "محمد ابراهيم صبرى ابراهيم",
    StudentId: "1827183",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "55",
    StudnetName: "اسلام محمود عبد المجيد محمد احمد",
    StudentId: "1827193",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "56",
    StudnetName: "سيد خالد سيد عبده الغندور",
    StudentId: "1827195",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "57",
    StudnetName: "محمود خالد سعيد المنشاوى",
    StudentId: "1827205",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "58",
    StudnetName: "جورج عصام حلمى يسي",
    StudentId: "1827213",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "59",
    StudnetName: "شروق مسعد عبد الهادى عامر",
    StudentId: "1827222",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "60",
    StudnetName: "احمد حسين سالم احمد",
    StudentId: "1827230",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "61",
    StudnetName: "عمر محمد عبدالله احمد",
    StudentId: "1827237",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "62",
    StudnetName: "محمود محمد على محمود على",
    StudentId: "1827239",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "63",
    StudnetName: "رفيف عصام علي الماحي",
    StudentId: "1827250",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "64",
    StudnetName: "محمد سعيد عيد مصطفى",
    StudentId: "1827254",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "65",
    StudnetName: "محمد عاطف محمد ربيع",
    StudentId: "1827257",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "66",
    StudnetName: "عمر ماهر زكريا مصطفى",
    StudentId: "1827261",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "67",
    StudnetName: "محمد عادل حسن المشهور فرغلى على حسن",
    StudentId: "1827265",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "68",
    StudnetName: "عبد الرحمن احمد عبد المتجلى سعيد",
    StudentId: "1827273",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "69",
    StudnetName: "ياسر محمد عبد المنعم على",
    StudentId: "1827290",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "70",
    StudnetName: "اسماء عبد الفتاح محمد",
    StudentId: "1827300",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "71",
    StudnetName: "احمد على حسن محمد",
    StudentId: "1827308",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "72",
    StudnetName: "عبد الرحمن رمضان عبد التواب",
    StudentId: "1827315",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "73",
    StudnetName: "رضا محمد توفيق",
    StudentId: "1828717",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "74",
    StudnetName: "تقى هشام اسماعيل عبد اللطيف",
    StudentId: "1831056",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "75",
    StudnetName: "ضياء جمال محروس عباس",
    StudentId: "1927284",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
  {
    Code: "76",
    StudnetName: "علي أحمد فؤاد فؤاد عطا الله",
    StudentId: "2470123",
    Attendance: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    lastAttend: 1,
    totalAttendance: 1,
    Participation: "0",
    View: false,
  },
];
